.env.example
.github/workflows/deploy.yml
.gitignore
Gemfile
Gemfile.lock
config.ru
db/database.rb
lib/loader.rb
lib/repositories/example_repository.rb
lib/server.rb
lib/services/example.rb
manifest.yml

This adds a deployment pipeline for on merge to main. Alongside this it also adds example code for connecting to a database and creating service classes. This is both to serve as a future example, but also to test that the loader/database connection is set up correctly.
It also adds `dotenv` for managing environement variables locally

Add deployment pipeline for main

---

lib/repositories/pages_repository.rb
lib/server.rb
spec/repositories/pages_repository_spec.rb

Pages form a linked list. Currently the client is responsible for
ensuring the consistency of the list.
This commit changes this by making sure new pages are 'appended' to the end
of the list. Deleting a page in the middle of the page list now connects
the two lists together. These changes mean there should only be one
connected list of pages.
This means clients are no longer able to create pages which random
'next' values. The update route hasn't been changed to keep that
possibility available, but maybe should be closed off too to ensure
consistency.

Change create/delete page to alter order

---

db/migrations/5_update_incorrect_next_page_attribute_value.rb
lib/repositories/pages_repository.rb
spec/db/migration_5_spec.rb
spec/repositories/pages_repository_spec.rb

Relates to https://trello.com/c/30BWYuYQ/42-bug-next-page-value-not-being-set-correctly
When new pages were being created for a
specific form we were setting the next page
attribute for all pages even if the page
wasn't linked to the form that we were updating.

Fix adding next page to other forms

---

Gemfile.lock
lib/api_v1.rb
lib/repositories/forms_repository.rb
lib/server.rb
spec/repositories/forms_repository_spec.rb

The [previous privacy policy PR](https://github.com/alphagov/forms-api/pull/61) added the relevant fields to the databse, but didn't include the logic to update them from the endpoints, this one adds that logic.
Trello card: https://trello.com/c/Q5wKHZ75/15-add-link-to-privacy-information-to-forms-api-needs-dev-review

Add privacy policy URL to update methods

---

db/migrations/9_rename_next_to_next_pages.rb
lib/api_v1.rb
lib/domain/page.rb
lib/repositories/pages_repository.rb
spec/db/migration_9_spec.rb
spec/domain/page_spec.rb
spec/repositories/pages_repository_spec.rb

We've decided to rename the `next` column in the pages table to `next_page`. This is because `next` is a reserved keyword in ruby and we want to save ourselves issues in the future. 
Before this is merged I'll need to make PRs in the admin and runner reflecting this change. 
I will also be updating this column to be an integer, not a string, but this will be part of a separate PR

Update next to next page

---

db/migrations/012_add_what_happens_next_to_forms.rb
lib/api_v1.rb
lib/repositories/forms_repository.rb
spec/db/migration_012_spec.rb
spec/repositories/forms_repository_spec.rb

This PR adds a field called "what_happens_next_text" field to the form table. Happy to hear any suggestions on a better name if you have one. 
relates to this trello ticket: https://trello.com/c/4mCMqpda/356-add-what-happens-next-to-the-confirmation-page-should-have
- N/A I've updated the documentation in (If any documentation requires updating)
- N/A README.md
- N/A Elsewhere (please link)

Add what happens next

---

db/migrations/013_add_contact_details_to_forms.rb
lib/api_v1.rb
lib/repositories/forms_repository.rb
spec/db/migration_013_spec.rb
spec/repositories/forms_repository_spec.rb

https://trello.com/c/92U8erwW/18-add-form-specific-contact-details-for-support-to-forms-api-should-have
Adds four contact details columns to the forms model - `support_email`, `support_phone`, `support_url`, `support_url_link`

18 add form specific contact details for support to forms api

---

lib/api_v1.rb

None of our other params have specific types. There also had a problem with the requests coming from forms-admin where the value was being sent as strings in the call. The database column is setup as boolean so should fail any requests that try to set it to non-boolean values.

Switch is_optional from TrueClass to String

---

db/migrations/015_add_declaration_to_forms.rb
lib/api_v1.rb
lib/repositories/forms_repository.rb
spec/db/migration_015_spec.rb
spec/repositories/forms_repository_spec.rb

https://trello.com/c/T2Hl1g1p/232-add-custom-declaration-field-for-the-check-your-answers-page-to-the-api
This PR adds a new field to forms - declaration text. This field store the declaration a form creator would like the form-filler to see before submitting the form.

Add declaration_text to forms

---

db/database.rb
lib/api_v1.rb

Create a single instance of the  Sequel Database object and use it to run queries across all API requests. Previously a new Sequel Database object was being created for every API request which were not being garbage collected and so eventually exhausted memory.
Forms-api micro service routinely crashes after exhausting available memory, as shown in the memory stats from production below. The app logs note 'app crashed' and the container exits with status code 137.
The issue can be replicated locally with the docker-compose set-up and sending requests to simply get the first page of a form. The heap dumps showed a linear build up of database related objects and memory allocation with each api call. This seems to be because a new Sequel database object was being instantiated each time with …

Setup a Database Connection Once

---

db/migrations/016_add_question_section_completed_to_form.rb
lib/api_v1.rb
lib/repositories/forms_repository.rb
lib/repositories/pages_repository.rb
spec/db/migration_015_spec.rb
spec/db/migration_016_spec.rb
spec/repositories/forms_repository_spec.rb
spec/repositories/pages_repository_spec.rb

- add a new boolean attribute called `question_section_completed` to `forms` table
- default value is set to false
- Resets this attribute back to `false` if a form creator creates/edits another page after marking the question_section_completed to true.
Relates to https://trello.com/c/xyAJo5Wp/187-forms-api-store-progress-for-page-questions-section-of-forms:

Allow form-creators to mark "Questions" task as complete

---

Gemfile.lock
db/migrations/017_add_declaration_section_completed_to_form.rb
lib/api_v1.rb
lib/repositories/forms_repository.rb
spec/db/migration_017_spec.rb
spec/repositories/forms_repository_spec.rb

Adds a new `declaration_section_completed` field to the form so that the user can mark the declaration as complete.
Unlike the `question_section_completed` field, we're not doing anything special here to reset the field when the declaration text is edited. This is because the declaration text and the `declaration_section_completed` question are in the same form, so the user isn't able to set the declaration text without also setting the declaration completion status to their desired value.
Trello card: https://trello.com/c/6kzPVxj1/286-add-are-you-finished-section-to-the-form-admin-add-a-declaration-task
Related admin PR: https://github.com/alphagov/forms-admin/pull/193
- [n/a] Elsewhere …

Add declaration completion status field

---

db/migrations/018_add_answer_options_to_page.rb
lib/api_v1.rb
lib/domain/page.rb
lib/repositories/pages_repository.rb
spec/db/migration_018_spec.rb
spec/domain/page_spec.rb
spec/repositories/pages_repository_spec.rb

Adds an `answer_settings` JSON column to the pages object. When returned from the API it will look something like this:
```json
"answer_settings": {
"allow_multiple_answers": true,
"selection_options": [
{"name": "Option 1"},
{"name": "Option 2"},
]
}
```
The intent is for this field to be flexible for different answer types - for example, this field will likely end up containing flags for autofill related settings for other fields.  
Trello card: https://trello.com/c/bSqKTDu8/224-add-selection-question-type-to-api

Add selection answer type and its options

---

db/migrations/019_add_page_order_to_form.rb
lib/api_v1.rb
lib/repositories/pages_repository.rb
spec/db/migration_019_spec.rb
spec/repositories/pages_repository_spec.rb

Currently users cannot change the order of pages in a form - they must
delete and recreate them.
The API returns pages ordered by id, when serving a form. This order is
used to display the pages in the admin's page list. This works because
the page.id always increases, and because the user has no way of moving
pages.
Pages in a form use the .next_page attribute to form an implicit linked
list. The start_page acts as the head of the list.
The runner uses the `start_page` attribute, which is not stored in the
database and is calculated by the API when retrieving a form, based on
lowest page id. It then moves from page to page using the id found in
the next_page attribute.
Adding reordering
This PR introduces two new endpoints for moving a page earlier and later
in the order of a form. This …

Add feature: reordering the pages in a form

---

lib/api_v1.rb
spec/db/migration_018_spec.rb
spec/domain/page_spec.rb
spec/repositories/pages_repository_spec.rb

This renames a field to make life slightly easier in the admin part of this work.
Shouldn't require a migration because this is part of a JSON column, so the table doesn't need to change, and no forms exist yet with this setting applied.
Trello card: https://trello.com/c/9AKruIBG/321-add-selection-question-type-to-admin-radio-buttons-only
Related runner PR: https://github.com/alphagov/forms-runner/pull/203 

Rename 'allow multiple answers'

---

lib/api_v1.rb
spec/domain/page_spec.rb
spec/repositories/pages_repository_spec.rb

Adds some options rewuired for the autocomplete changes:
- adds a 'name' answer type for the various ways of asking for a name
- adds a 'text' answer type (which will replace the existing short/long text options)
- adds a 'title needed' field to the answer_settings for the person's title
- adds an 'input type' field to the answer_settings - this will be used for:
- determining which type of name input is displayed in the runner
- determining which type of date field is displayed in the runner
- determining which type of address field is displayed in the runner
- determining which kind of text input to use in the runner.
Trello card: https://trello.com/c/efuBewje/391-persons-name-implementation-of-autofill-work-in-production
- [n/a] I've updated the documentation in (If any documentation …

Add options for autocomplete work

---

spec/request/forms_spec.rb
spec/request/pages_spec.rb

Most of the current tests are unit tests and don't cover the controller.
There are tests for the repositories, migrations and page domain object
as well as some tests which cover the API_KEY and ping routes.
This commit adds request tests for the forms and pages routes.
The tests aim to cover the external API so that large changes can be
made while preserving the interface and calling conventions.
Trello card: https://trello.com/c/bS0dm5OP/356-add-contract-tests-to-the-api

Add Rspec request tests

---

.github/workflows/ruby.yml

- includes rails-api branch in the ruby workflow
- I noticed that we were not using the same version of postgres and instead should be using v11
Trello card:

Include rails-api branch in ruby spec/linting workflow 

---

.github/workflows/ruby-on-rails.yml
.github/workflows/ruby.yml
Gemfile
Gemfile.lock
app/controllers/api/v1/forms_controller.rb
app/controllers/application_controller.rb
app/models/form.rb
config/routes.rb
db/migrate/20221216112945_create_forms.rb
db/schema.rb
spec/factories/forms.rb
spec/models/form_spec.rb
spec/request/forms_spec.rb

Adds RESTful endpoints for forms model:
- GET `api/v1/forms?org=xxx` - get a list of forms for a specific organisation
- GET `api/v1/forms/:id` - shows an existing form
- POST `api/v1/forms` - creates a new form
- PUT `api/v1/forms/:id` - updates an existing form
- DESTROY `api/v1/forms/:id` - deletes an existing form
You should be able to run this locally in place of your existing forms-api. You should be able to see a list of forms on the home page and be able to create a new form but the form (i.e task list page) itself will not display until we have added pages model.
Trello card: https://trello.com/c/Lltmxkb6/365-migrate-forms-to-rails-api

Create forms endpoints

---

app/models/form.rb
spec/request/api/v1/forms_controller_spec.rb

Rails was not deleting the pages that existed for a form that was about to be deleted. This happened locally on my machine and on staging when testing out the rails api version.
Error message:
PG::ForeignKeyViolation: ERROR:  update or delete on table "forms" violates foreign key constraint "fk_rails_ffa7b626f0" on table "pages" DETAIL:  Key (id)=(256) is still referenced from table "pages".
Trello card:

Fix FK violation error when deleting forms that have pages

---

config/settings/development.yml

Docker uses 'development_key' as the API key if there is not one set through the environment variables.
This commit changes the current default to 'development_key' to blank in development.

Change local API key to previous value

---

app/controllers/api/v1/pages_controller.rb
spec/request/api/v1/pages_controller_spec.rb

When a form creator makes changes to a page, the question_section_completed value for a form should be reset to false. 
This is used to show the status in the tasklist.
This commit updates the value when pages are created, updated or deleted.
Trello card:

Reset pages complete

---

config/initializers/sentry.rb

Disable Sentry Transactions
Sentry Transactions can be used to monitor application performance by
sampling transaction data. We are not using this aspect of Sentry and
have decided to turn it off.
Setting this to `0.0` or removing it all together will disable transaction data: https://docs.sentry.io/platforms/ruby/guides/rails/configuration/options/#tracing-options
I've opted to set it to `0.0` so there is some on-going record for the future that we have intentionally disabled this feature.

Disable Sentry Transactions

---

app/controllers/api/v1/pages_controller.rb
spec/request/api/v1/pages_controller_spec.rb

Edits the strong params to allow input type to be a hash for certain inputs - and enables this for the address input type.
Trello card: https://trello.com/c/zdoo448d/382-address-implementation-of-autofill-work-in-production
Related PRs:
- Admin: https://github.com/alphagov/forms-admin/pull/270
- Runner: https://github.com/alphagov/forms-runner/pull/229

Allow input type hash in strong params

---

app/controllers/api/v1/forms_controller.rb
app/models/form.rb
spec/request/api/v1/forms_controller_spec.rb

Ignore attributes that might come in from end users (api should be responsible for setting these two attributes).
Fixed the formatting of those two attributes
Trello card:

Fix created_at/updated_at

---

app/controllers/api/v1/pages_controller.rb
app/models/page.rb

Adds the new name type to the list of allowed answer types, and allows it to send an `answer_settings` hash in the strong params.
Trello card: https://trello.com/c/efuBewje/384-persons-name-implementation-of-autofill-work-in-production

Strong params changes for name input

---

.rubocop.yml
Gemfile.lock
app/controllers/api/v1/pages_controller.rb
config/settings.yml
config/settings/development.yml
db/migrate/20230126133557_convert_date_to_other_date.rb
db/migrate/20230126135721_convert_address_to_uk_address.rb
db/migrate/20230126141136_convert_old_text_fields_to_new_text_fields.rb
db/schema.rb
spec/config/settings_spec.rb
spec/factories/forms.rb
spec/migrations/convert_address_to_uk_address_spec.rb
spec/migrations/convert_date_to_other_date_spec.rb
spec/migrations/convert_old_text_fields_to_new_text_fields_spec.rb
spec/request/api/v1/pages_controller_spec.rb
spec/spec_helper.rb
spec/support/migration_helpers.rb

Adds migrations for the pre-existing answer types (address, date, single line of text, multiple lines of text) that have had answer settings pages added.
Also includes some logic to allow the API to handle pages with the legacy `single_line` and `long_text` inputs in the `create`, `update` and `show` actions. This is behind a feature flag `accept_legacy_answer_types` - this will default to `true` and should be changed to `false` as soon as the `autofill_answer_types` feature flag in admin is set to `true`. We only need to add this for the text answer types - `address` and `date` are already sending `answer_settings` to the API. 
Still to do:
Trello card: https://trello.com/c/RDzeLJqz/461-write-migrations-for-changed-autofill-fields
- [n/a] I've updated the documentation in (If any …

Add migrations for autofill answer types

---

app/controllers/api/v1/forms_controller.rb
config/routes.rb
spec/factories/forms.rb
spec/request/api/v1/forms_controller_spec.rb

This new endpoint will have all the information a client would need to produce the specific form
i.e Form info and all pages included in the JSON response. 
This helps where our services are making two calls for every web page request. one to get
the form and another to get all the pages for that form.
For the time being, this will use existing Form records but once we have draft/live versions implemented
this would return whatever version is live for the existing form.
New endpoint is `api/v1/forms/:form_id/live` 
Trello card:

New /live endpoint

---

app/controllers/api/v1/forms_controller.rb
spec/request/api/v1/forms_controller_spec.rb

Currently this sorting is done on the forms-admin. This is not great especially when we come to adding pagination to this list of forms it could cause a problem and its better for the
api to serve data is a consistent order.
Trello card:

Add sorting to list of forms by organisation

---

config/database.yml

Suffix `_development` to the name of the development database to match the pattern used on other databases in this app and the forms-admin app.
The name of the development database is currently a little surprising.

Rename development database to be more consistent

---

Gemfile
Gemfile.lock
app/models/form.rb
app/models/page.rb
db/migrate/20230227143427_create_versions.rb
db/migrate/20230227143428_add_object_changes_to_versions.rb
db/schema.rb
spec/models/form_spec.rb
spec/models/page_spec.rb
spec/rails_helper.rb

This is the outcome of https://github.com/alphagov/forms-api/pull/174 where we were initially thinking of using papertrail to snapshot draft/live versions but we ran into issues with associations records and when attempting to delete them.  We decided now to just use Papertrail for auditing purposes and for single record backup/restoration.
- Adds PaperTrail gem
- configures Form/Page to be versioned
This data isn't being surfaced to users at the moment but we can still use this for support queries and eventually it will be surfaced to users when we get to versioning. 
Trello card:

Add auditing to our models

---

app/models/form.rb
app/models/made_live_form.rb
db/migrate/20230302161521_create_made_live_forms.rb
db/migrate/20230303132811_add_initial_made_live_forms.rb
db/schema.rb
spec/factories/made_live_forms.rb
spec/models/form_spec.rb
spec/models/made_live_form_spec.rb
spec/request/api/v1/forms_controller_spec.rb

Creates a new published form table to store a version of forms and pages as a single JSON blob.
Tweaks how make_live and live endpoints work to use the stored live version JSON blobs.
Trello card: https://trello.com/c/7T5Yp818/426-implement-draft-live-versioning-in-backend

Creating made_live_forms

---

app/models/form.rb
spec/models/form_spec.rb

This is a temporary fix for the time being. We have a ticket to look at deleting forms in general and we will need to think how we delete forms in general. Also from an e2e POV, we go through the whole process of creating a form, making it live, filling it in and then after a form submission we try to delete the live form. Without this temporary fix our e2e tests will continue to fail when trying to delete the live form.
Trello card:

Allow live forms to be deleted

---

app/controllers/api/v1/access_tokens_controller.rb
app/controllers/application_controller.rb
app/models/access_token.rb
config/routes.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml
db/migrate/20230309213951_create_access_tokens.rb
db/migrate/20230315130919_add_last_accessed_at_to_access_tokens.rb
db/schema.rb
spec/config/settings_spec.rb
spec/factories/access_tokens.rb
spec/models/access_token_spec.rb
spec/request/api/v1/access_tokens_controller_spec.rb
spec/request/application_controller_spec.rb

Currently we only support one single key that is a set environment variable secret. This makes it harder for us to create keys for different use cases eg. different keys for each client that might use it or tech support devs needing to call endpoints.
This PR adds the following:
- Adds a new setting to toggle authentication. Its enabled by default for rails production environments but disabled for local development or testing. It can be enabled in local dev or specific tests depending on the needs of the developer.
- Adds a new database table to store a list of tokens. Tokens can be disabled and we will record the last time a specific token  was used
- Refactors the authentication mechanism so that that requests can be authorised either using the older header request method or if that …

Add support for multiple authentication keys

---

app/controllers/api/v1/access_tokens_controller.rb
config/routes.rb
spec/request/api/v1/access_tokens_controller_spec.rb

using an existing active token making  a GET request to `api/v1/access-tokens/caller-identity` will return the details for token that's being used in the existing request.
Trello card:

New end point to return details of current token being used for the request

---

app/controllers/api/v1/forms_controller.rb
spec/request/api/v1/forms_controller_spec.rb

The problem with making the org param required is that it stops us from searching for all forms across all organisations.
If you pass in `org` as a query param (which `forms-admin` and `forms-runner` already do), it will return a list of forms for that organisation. If you leave off the query param it will return a list of forms.
Trello card:

Return a list of forms across all organisations

---

app/controllers/api/v1/forms_controller.rb
config/routes.rb
spec/request/api/v1/forms_controller_spec.rb

we wanted an easy way to return a draft form and its pages in one request. This is almost identical show_live except instead of returning a live form and its pages, it returns a draft form and its pages.
Trello card:

Add show-draft endpoint

---

app/controllers/api/v1/pages_controller.rb
app/models/form.rb
app/models/page.rb
db/migrate/20230324113043_update_live_at_date_times.rb
db/migrate/20230324120801_remove_live_at_from_forms.rb
db/schema.rb
spec/factories/forms.rb
spec/factories/made_live_forms.rb
spec/factories/pages.rb
spec/models/form_spec.rb
spec/models/made_live_form_spec.rb
spec/models/page_spec.rb
spec/request/api/v1/forms_controller_spec.rb

While working on https://trello.com/c/845sNCtW I found there were a bunch of things that it would be good to clean up in our models to make it easy to tell when a form had a draft version and/or a live version.
I've split those changes out into a separate PR, to break things up a bit.
- It was hard to write model specs that change a form or a page while doing the same bookkeeping as the controllers, we move that business logic into a new `FormUpdateService`
- The datetime stamps for live_at and made_live_forms.last weren't consistent with the updated_at of the form, so we couldn't compare reliably
- The logic for creating a JSON form blob was scattered all over in our code and in our specs, we restore the `snapshot` method to bring it all into one place
Those are the major ones, there are …

Refactors to draft/live functionality and associated tests

---

app/models/form.rb
spec/models/form_spec.rb

Commit 38b3a2c broke the forms-runner for newly made live forms, as form blob did not include the live_at attribute required for validation of the form [[1]], [[2]].
For backwards-compatibilty, this commit adds the live_at datetime back into the form blob for made live forms. For draft form versions, live_at is not needed, so we leave it out.
[1]: https://github.com/alphagov/forms-runner/blob/main/app/models/form.rb#L25-L30
[2]: https://github.com/alphagov/forms-runner/blob/31a0d62dab8a950d0df59e9a652c5006d9362d63/app/controllers/forms/base_controller.rb#L66
Fixes `invalid live_at time` errors seen in https://govuk-forms.sentry.io/issues/4034044478/

Fix form-runner

---

app/models/condition.rb
app/models/page.rb
db/migrate/20230324091733_create_conditions_table.rb
db/migrate/20230331141402_add_skip_to_end_to_conditions.rb
db/schema.rb
spec/factories/conditions.rb
spec/models/condition_spec.rb

Trello card: https://trello.com/c/FbZxLSWp/561-api-migration-for-simple-routing
This adds a Conditions table, which contains a set of references to the Pages table. 
There's a bit of complexity around which references are necessary and which are optional. The idea is that a Condition has to be attached to a specific page, which is the `routing_page`. This is a mandatory relationship, and deleting the page destroys this condition. 
There are also two other page references, one to the page whose answer will be checked, the `check_page`, and the other to whom the user will skip to if the condition is met, the `goto_page`. If the user deletes the associated page, the reference is simply removed, while the condition remains.
Updating comment for trello testing!
31/03/23 **Update**: I've added …

Create conditions table and model

---

db/schema.rb

db schema wasn't in sync with the db but `rails db:migrate` wasn't run after comments were added to migration.  https://github.com/alphagov/forms-api/pull/231/files#diff-9dfba9f77e4f88d15e2e6cca412a17b4079d455b7990f2e7f0b27c92402d418bR4-R6
Trello card:

fix db schema which hadn't been updated after adding column comments

---

app/models/form.rb
app/models/page.rb
spec/request/api/v1/pages_controller_spec.rb

Any conditions that are associated with a page via the "routing_conditions" associtation will now be included with the page.
The result is a new key being available on pages, `routing_conditions`, which will contain an array of all the page's associated routing conditions, or an empty array if there aren't any.
Trello card: https://trello.com/c/VZNwPF1R/622-coordinate-basic-routing-with-draft-live-work

Include conditions in json bundling api calls

---

Gemfile.lock

Without this, installing packages on x86_64 macs always changes the gemfile.lock.
Trello card:

Add x86_64-darwin-22 to Gemfile.lock

---

app/models/condition.rb
app/models/form.rb
app/models/page.rb
spec/models/condition_spec.rb
spec/request/api/v1/conditions_controller_spec.rb
spec/request/api/v1/pages_controller_spec.rb

This is the first time that `forms-api` will be returning custom errors for the client to handle.  This PR adds a new method called `validation_errors` which dynamically evaluates the data when it is called to check if the route is valid. If it is not then it returns an object with a shorthand human readable error. `forms-admin` will use this value to look up the full user friendly error description. We did this because `forms-api` would not know what language the `forms-admin` is using without us also including the language in every request. 
```json
{
"id": 33,
"check_page_id": 4,
"routing_page_id": 4,
"goto_page_id": 12,
"answer_value": "Cat",
"created_at": "2023-04-25T09:14:55.978Z",
"updated_at": "2023-04-28T10:49:27.283Z",
"skip_to_end": false,
"validation_errors": [
{
"name": …
```

Add routing warnings - Go To page doesn't exist

---

app/models/form.rb
spec/models/form_spec.rb
spec/request/api/v1/forms_controller_spec.rb

This is an over hang from the draft/live feature work we did. We needed to be able to support forms-runner before it had three different modes to display forms in (preview-live, preview-draft & Live). Before that work was done forms-runner could only display live forms and preview-form (ie no way to work out if its a draft/live it should be previewing).
Now what should happen is if a form is created and has never been made live then we should be returning 404 when the show_live endpoint is called rather than returning the draft form.
I've tested this locally and forms-api and forms-runner return 404 (and correct 404 page in the runner) when you try to view a form that has never been live.
Trello card: https://trello.com/c/yTVLXp4d/746-forms-api-should-return-404-when-asked-for-a-version-of …

Return 404 if not live form exists

---

app/models/condition.rb
spec/factories/pages.rb
spec/models/condition_spec.rb

Return a validation error if the page selection options are edited/removed and the conditions answer value is no longer a valid option for the user to select from
Trello card: https://trello.com/c/dGvEYmsk/712-add-answer-does-not-exist-error-to-conditions-in-api

Add warning_answer_doesnt_exist to condition model

---

app/models/condition.rb
spec/models/condition_spec.rb

The API needs to calculate whether the page being directed to is going to result in at least one question page being skipped - otherwise, the route will, regardless of the condition being triggered, simply go on to the next page. This isn’t a breaking error necessarily, but it does represent a trivial condition being in place
Trello card: https://trello.com/c/K57UF6bv/738-add-routing-goes-to-the-next-page-error-to-conditions-in-api

Warn users if a route that is the next page

---

app/models/condition.rb
spec/models/condition_spec.rb

The API needs to calculate the whether the routing for a given condition makes sense from a sequencing perspective. That is, the question that’s being checked takes place before the question that’s being directed to. This should only happen when a user reorders questions.
Trello card: https://trello.com/c/iFDqUmDc/739-add-question-routing-is-out-of-sequence-error-to-conditions-in-api

Warn users if their route ends up creating an endless loop

---

app/models/page.rb
spec/models/page_spec.rb

We warn users when they edit their pages and changing the answer type will delete any existing routes.
While reviewing this part of the page, it was noted that the current implementation would reset the
form "question section completed" attribute every time a user pressed "save" regardless of whether there was anything to be changed. This has been changed in this commit so that we only attempt to save the page and modify form attributes if there are actually changes.
Trello card: https://trello.com/c/hC31J4xI/737-add-invalid-answer-type-warning-to-forms-api-and-delete-route

Delete existing routes if answer_type is not selection

---

app/models/page.rb
spec/models/page_spec.rb

Fixes a bug with routes being deleted when they shouldn't. Essentially whenever a selection question was saved, the question's route would be deleted too - regardless of whether the answer type had actually changed. As far as I can tell this is because the check we were doing - `answer_type_previously_was` - only tells us that the page was a selection question before, not whether it's actually changed.
Trello card: None

Fix issue with routes being deleted when answer type hasn't changed

---

app/models/condition.rb
app/models/form.rb
app/models/page.rb
spec/models/condition_spec.rb
spec/models/form_spec.rb
spec/models/page_spec.rb
spec/request/api/v1/forms_controller_spec.rb
spec/request/api/v1/pages_controller_spec.rb

- Adds a validation to the API so that a form can't be marked as `question_section_completed: true` if it has routing validation errors
- Adds a `has_routing_errors` method to conditions, pages and forms, and makes these available in the API response to make checking this easier in forms-admin
In theory this validation should never actually fail, since forms-admin should only send the save request if the form is in a valid state, but this gives us some extra confidence.
Trello card: https://trello.com/c/W5mLjhd3/804-prevent-users-marking-the-pages-section-as-complete-while-there-are-routing-errors

Prevent marking questions section complete when there are routing errors

---

app/models/form.rb
spec/models/form_spec.rb

This is required so that trial users without organisations can create forms.
Trello card: https://trello.com/c/8kysclWz

Allow forms to not have an organisation set

---

Dockerfile

It is useful when looking at startup logs to be able to know what command was run, to understand the context of the log outputs.
See https://github.com/alphagov/forms-admin/pull/498 for more details.

Add shell command trace to container run command

---

app/controllers/api/v1/forms_controller.rb
config/routes.rb
spec/request/api/v1/forms_controller_spec.rb

When a user gets their account changed from trial to editor we want to have their forms added to their new organisation. This PR adds a specific bulk update endpoint to update the `org` for all forms with a matching `creator_id`. forms-admin can then use this endpoint when a user's role changes from trial to editor.
Trello card: https://trello.com/c/esvZIXnn

Add update_org_for_creator bulk update endpoint

---

app/controllers/api/v1/forms_controller.rb
spec/request/api/v1/forms_controller_spec.rb

By default `update_org_for_creator` returns 204 No Content, but to be consistent with other endpoints we should return 200 until we have a review of what status codes we should be returning for endpoints that conventionally would return no body in the response.
Trello card: https://trello.com/c/4Lxkorfb

Make update_org_for_creator endpoint return status

---

app/controllers/api/v1/forms_controller.rb
app/models/form.rb
config/routes.rb
db/migrate/20230615094934_add_organisation_id_to_forms.rb
db/schema.rb
spec/factories/forms.rb
spec/models/form_spec.rb
spec/request/api/v1/forms_controller_spec.rb

We want to associate forms with organisations using a stable key, however organisations slugs can change, so we want to change the key to be the primary key of the organisation table, the ID.
This PR adds a new attribute to the form model to store the organisation ID. To fully migrate will require other changes in other PRs, once the data has been copied across successfully we can then remove the old `org` attribute that held the slug.
Trello card: https://trello.com/c/pt9lphfe

Add organisation_id to form model

---

config/environments/production.rb

When a HTTP request includes query parameters it is useful to be able to see these in our logs. By default Lograge filters this out as it can contain sensitive information [[1]], but we don't have anything like that in our system.
This is especially useful at the moment when we are changing from using `org` slug to `organisation_id` (see PR #295, ticket https://trello.com/c/pt9lphfe), as without this logging we can't see what the admin app is sending to the api app for requests to `/forms`.
[1]: https://github.com/roidrage/lograge/blob/09bd96e1cb56f94841a64473e4195d413ce908fc/lib/lograge/log_subscribers/action_controller.rb#L21-L39

Add URL query params to logging messages

---

db/migrate/20230801100920_add_detailed_guidance_to_pages.rb
db/schema.rb
spec/request/api/v1/pages_controller_spec.rb

Trello card: https://trello.com/c/hu2VpKTR/931-store-a-questions-page-heading-and-detailed-guidance
Adding two columns for the detailed guidance work - the `page_heading` and `detailed_guidance_markdown` happy to take name suggestions on them!

Add heading and detailed guidance columns to pages

---

db/migrate/20230804113818_rename_pages_detailed_guidance_markdown_to_additional_guidance_markdown.rb
db/schema.rb
spec/request/api/v1/pages_controller_spec.rb

Rename pages detailed_guidance_markdown to match name used in forms-admin

Rename detailed_guidance_markdown column  to match forms-admin

---

app/controllers/api/v1/pages_controller.rb
app/models/page.rb
db/migrate/20230822123702_change_additional_guidance_markdown_to_guidance_markdown.rb
db/schema.rb
spec/factories/pages.rb
spec/models/page_spec.rb
spec/request/api/v1/pages_controller_spec.rb

Renaming the `additional_guidance_markdown` column to `guidance_markdown`. There's a corresponding change to admin here https://github.com/alphagov/forms-admin/pull/602

Remove 'additional' from guidance_markdown column

---

db/migrate/20230824141905_add_additional_guidance_markdown_column.rb
db/schema.rb
spec/request/api/v1/pages_controller_spec.rb

In order to deploy the column name change more easily, this adds back the old column so that we can swap more gracefully

Add additional_guidance_markdown column for deploy smoothing

---

Dockerfile
Gemfile
Gemfile.lock
app/models/page.rb
spec/models/page_spec.rb

We are pulling in `govuk-forms-markdown` gem for validations. Forms-admin will use the same validations that are in the gem but this is really a backstop to ensure that no invalid guidance_markdown is stored in the db and if it is invalid it should flag it up as an error.
Trello card: https://trello.com/c/CCmWlsUJ/958-implementing-markdown-in-forms-api

Add validation for guidance_markdown

---

app/controllers/api/v1/pages_controller.rb
app/controllers/application_controller.rb
app/models/page.rb
config/locales/en.yml
spec/models/page_spec.rb

Adding sensible hard limits to question_text, hint_text and page_heading
Trello card: https://trello.com/c/MAokcg4Y/1001-add-size-limit-to-question-text-pageheading-hint-text

Add max length validation to page question_text, hint_text and page_heading

---

app/controllers/api/v1/forms_controller.rb
app/models/form.rb
app/service/task_status_service.rb
spec/factories/forms.rb
spec/models/form_spec.rb
spec/request/api/v1/forms_controller_spec.rb
spec/service/task_status_service_spec.rb

Currently we have validation in forms-admin that prevents making a form live until certain conditions are met. However the api will happily make a form live if those conditions aren’t met.
This PR adds an updated task status service from forms-admin, and uses it validate the status of mandatory tasks prior to making a form live. It also adds task status data to the form data itself.
Unfortunately the submission email status depends on data in the forms-admin db, so this isn't included in the validation. Instead the submission email check is still done in forms-admin, and is combined with the `incomplete_tasks` and `task_statuses` from forms-api.
It would be great to hear other people's opinions on whether this refactor (in effect splitting the validation across forms-api and forms-admin) …

Add make live validation

---

app/controllers/api/v1/conditions_controller.rb
app/controllers/api/v1/forms_controller.rb
app/controllers/api/v1/pages_controller.rb
spec/request/api/v1/conditions_controller_spec.rb
spec/request/api/v1/forms_controller_spec.rb
spec/request/api/v1/pages_controller_spec.rb

Trello card: https://trello.com/c/1Wr1DCBT 
We want the API to respond with a resource when requests are made, even if it's a request to update or delete an object. As well as being more in line with other APIs (see the JSON::API spec for example [[1]]), this will also let us reduce the number of requests we need to make in the admin app.
For the simple traditional CRUD (Create, Read, Update, and Delete) operations the conventional responses are prescribed in the JSON::API spec. For some of our endpoints, they don't really fit into the RESTful/CRUD model, so I've just gone with what I think is most predictable/useful.
Note that technically the changes in this PR are breaking changes and should result in a new API version, but currently our API is internal only and none of the consumers …

Change API endpoints to respond with resource

---

app/controllers/application_controller.rb
config/application.rb

When searching Splunk for requests related to a particular page of a form it would be nice to be able to construct a query with `page_id=n`.
This PR adds the page ID to the log event JSON payload so that this will be possible in future.
See https://github.com/alphagov/forms-runner/pull/431 and https://github.com/alphagov/forms-admin/pull/668 for similar PRs for the runner and admin apps.
While adding this functionality I also noticed that we're not consistently logging `form_id` with every request, because the name of the param changes depending on the route. This PR also tries to fix that, so we get the `form_id` key in all relevant requests.
- Are …

Log page ID with requests and improve logging of form ID

---

Dockerfile

In commit 6979388 we used both the stable and edge repos for Alpine because we wanted OpenSSL 3 in our app image. However, OpenSSL 3 is the default version of OpenSSL in Alpine 3.17.0 [[1]]. So we no longer have a need for edge.
With Alpine 3.17 at the time of this commit fetching the edge repo index fails, so building this Dockerfile fails with the error:
```
Step 24/35 : RUN apk update
---> Running in 247913f7587d
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/main: BAD signature
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/main: No …
```

Remove Alpine edge repositories from Dockerfile

---

app/controllers/api/v1/forms_controller.rb
app/controllers/application_controller.rb
spec/request/api/v1/forms_controller_spec.rb

For requests that are routed to the FormsController, the form ID is named `:id` rather than `:form_id`, so the logging setup needs to be slightly different. This commit adds a specialisation of the `append_info_to_payload` method to the `FormsController` class so we get the correct behaviour when necessary.
Thanks @thomasiles for pointing out the issue and suggesting that we can use OOP to fix this (see https://github.com/alphagov/forms-api/pull/339#discussion_r1358180399).

Fix logging of form_id in FormsController

---

app/controllers/api/v1/access_tokens_controller.rb
app/models/access_token.rb
config/routes.rb
spec/request/api/v1/access_tokens_controller_spec.rb

Renames the name of the placeholder in the routes for access tokens from `:id` to `:token_id`, to make it harder to confuse the parameter with the form ID of other routes.
I also expanded the responses from the access token endpoints so that you actually get the ID when you create a token.

Rename param for access tokens route

---

Dockerfile

[Trello card](https://trello.com/c/S3jDIsp0/243-update-app-docker-images)
This PR updates the docker alpine version from 3.17 to 3.18
This has been deployed to dev and is working as expected. 

bump docker alpine version to 3.18

---

spec/models/form_spec.rb

This was confusing before, and we are about to add a spec on making forms un-live without deleting the parent form.

Update make_live_form spec descriptions

---

app/controllers/api/v1/forms_controller.rb
app/models/form.rb
config/routes.rb
spec/models/form_spec.rb
spec/request/api/v1/forms_controller_spec.rb

Trello card: https://trello.com/c/E6iLOdFK/1180-add-a-un-alive-switch-for-a-form
If a form hits any sort of trouble, we need a reliable way to make it offline

Add code that makes forms un-live

---

lib/tasks/forms_admin.rake
spec/lib/tasks/forms_admin_spec.rb

This is a follow on from https://github.com/alphagov/forms-api/pull/363 and adds a rake task to call that code to make a form no longer live.
Trello card: https://trello.com/c/E6iLOdFK/1180-add-a-un-alive-switch-for-a-form

Add rake task to make a form not live

---

db/migrate/20221216112945_create_forms.rb
db/migrate/20221219153156_create_pages.rb

These were only made explicit to support a potential rollback to Grape as we migrated from there to Rails in the past. However this is now causing us issues as part of our Rails 7.1 upgrade [1]
[1]: https://github.com/alphagov/forms-api/actions/runs/6876807358/job/18703161928?pr=369

Remove timestamp constraint

---

db/seeds.rb

Make it quicker to get a useful test form created when doing local development.
This PR adds a copy of @DavidBiddle's 'All question types' form that already exists in dev at `/forms/71/live`. If you want to add this to your database you can simply run `rails db:seed`

Add database seed with all question types form

---

db/migrate/20231116142411_add_what_happens_next_markdown_to_forms.rb
db/schema.rb
spec/models/form_spec.rb
spec/request/api/v1/forms_controller_spec.rb

Trello card: https://trello.com/c/AbPj2LRr/1191-allow-markdown-on-confirmation-page-what-happens-next-content
Adds a null `what_happens_next_markdown` field to the form. Also adds this null field to the most recent `made_live_form`.
To do in other PRs:
- add logic in the runner (https://github.com/alphagov/forms-runner/pull/496) and admin to use the markdown field if it's present, and the HTML if not 
- convert the HTML content in the API into markdown and store it in this new field
- cleanup: delete the old field and all the logic related to it which we no longer need …

Add empty what happens next markdown field

---

Gemfile
Gemfile.lock
lib/tasks/what_happens_next_markdown.rake
spec/lib/tasks/what_happens_next_markdown_spec.rb

Trello card: https://trello.com/c/AbPj2LRr/1191-allow-markdown-on-confirmation-page-what-happens-next-content
Adds a rake task which takes the content of the what_happens_next_text field, converts it to markdown using the ReverseMarkdown gem, then saves this markdown in the to the what_happens_next_markdown field that we added in #371. It also adds this markdown to the made live form.
Doing this as a rake task means we're not stuck with a migration that's dependent on a specific gem, and we've previously said we'd consider reserving migrations for schema changes. The downside is we'll have to run the task manually in each environment.
To do in other PRs:
- cleanup: delete the old field and all the logic related to it which we no longer need
- …

Convert what happens next content to markdown

---

spec/spec_helper.rb

The `--only-failures` and `--next-failure` options in RSpec make it much quicker to re-run tests that have failed, however they need the `example_status_persistence_file_path` configuration to be set [[1]].
This commit tells RSpec to save a file `examples.txt` into the a new folder in the Rails app's `tmp` folder; this seems like as good a place as any, as it's already ignored by git and docker, and is clearly named.
[1]: https://rspec.info/features/3-12/rspec-core/command-line/only-failures/

Configure RSpec to allow the --only-failures CLI option

---

config/routes.rb
spec/request/application_controller_spec.rb

rails 7.1 introduced a health check endpoint by default. This default endpoint is called `/up`. Instead of returning 200 with the body response of `PONG`, it will return 200 if the app is healthy and it will output a html page with the background color set to green. If there is an issue it will return 500 error and the html page will have a red background.
We will need to update our infrastructure to use /up instead `/ping` and then we can remove our custom heartbeat controller.
A simple test was added as part of this commit, not to test Rails implementation but as a means to check the functionality is present in the application and should fail if someone deletes the route in error.
see https://github.com/rails/rails/blob/f481353150c100dbd944d5aa84f2480264cd723c/railties/lib/rails/health_c …

add default rails healthcheck endpoint

---

app/controllers/application_controller.rb
config/settings.yml
config/settings/development.yml
config/settings/test.yml
spec/config/settings_spec.rb
spec/request/application_controller_spec.rb

In other apps we call this setting `Settings.forms_api.auth_key`. It would be helpful if this setting had the same name in all apps, because we could set it everywhere with one environment variable.
This commit renames the setting key in forms-api to match what is currently in forms-admin and forms-runner.

Rename authentication_key to auth_key

---

app/controllers/application_controller.rb
config/application.rb
spec/request/application_controller_spec.rb

We want to be able to correlate our Elastic Load Balancer logs with app logs. This is particularly useful when there is a `460` error because the client has closed the connection for taking too long.
This PR adds the `X-Amzn-Trace-Id` header [[1]] to our request logging.
[1]: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

Add AWS application load balancer trace ID to logs

---

Gemfile
Gemfile.lock
app/models/form.rb
app/state_machines/form_state_machine.rb
db/migrate/20240124160123_add_state_column_to_form.rb
db/schema.rb
spec/rails_helper.rb
spec/requests/api/v1/forms_controller_spec.rb
spec/spec_helper.rb
spec/state_machines/form_state_machine_spec.rb
spec/support/shared_examples/state_machine.rb

- https://github.com/alphagov/forms-api/pull/414
This PR adds a state column (but doesn't populate it) and introduces a basic state machine which is not integrated into the forms model just yet.
See individual commit messages when reviewing
```mermaid
---
title: Form states and events called to transition to state
---
stateDiagram-v2
Draft --> Live : make_live!
Draft --> Deleted : delete_form!
live_with_draft: Live with draft
Live --> live_with_draft : create_draft_from_live_form!
live_with_draft --> Live : make_live!
```
Trello card:  https://trello.com/c/YTzyf7wz/1339-implement-better-state-of-forms-tracking
- Do the commit messages explain why the changes were …

add state column to form model and bare bones state machine

---

app/models/form.rb
spec/lib/tasks/forms_admin_spec.rb
spec/models/form_spec.rb
spec/requests/api/v1/forms_controller_spec.rb

- https://github.com/alphagov/forms-api/pull/425 needs to be deployed first
This is the last piece of the puzzle, with these changes forms-admin & forms-runner will be able to identify a form's status by the state column. Eventually, we will want to remove these methods but we might want to keep them around as it does allow forms-api to control which statuses should be considered draft or live. forms-admin uses these methods to show/hide the draft/live status tags to users.
Once this is merged we can look at adding Archive state 
Trello card: https://trello.com/c/YTzyf7wz/1339-implement-better-state-of-forms-tracking
- Do the commit messages explain why the changes …

Change has_draft_version & has_live_version to use form state column

---

app/models/form.rb
app/state_machines/form_state_machine.rb
spec/lib/tasks/forms_admin_spec.rb
spec/models/form_spec.rb
spec/requests/api/v1/forms_controller_spec.rb
spec/state_machines/form_state_machine_spec.rb

This adds a new event to state machine called `archive_live_form!` which for the time being will transition a live/live_with_draft form back to initial `draft` state. This is because the current `make_unlive` form method deletes all `made_live_forms` records and leaves the form in an invalid state of `live`. I think the event can stay as part of archive but when we come to do the archive state we can change the transitions in this event to point to archive/archive_with_draft state
```mermaid
---
title: Form states and events called to transition to state
---
stateDiagram-v2
Draft --> Live : make_live!
Draft --> Deleted : delete_form!
live_with_draft: Live with draft
Live --> live_with_draft : create_draft_from_live_form!
live_with_draft --> Live : make_live!
```
```mermaid
---
title: Form …
```

add `archive_live_form` state machine event to transition live form to draft

---

db/migrate/20240201145400_remove_page_order_from_form.rb
db/schema.rb
spec/factories/forms.rb
spec/models/form_spec.rb
spec/requests/api/v1/forms_controller_spec.rb

This column is obsolete and was created before Jan 2023 when forms-api was not using rails. It was initial created to start an array of page ids in a particular order but when we moved over to rails we switched over to using acts_as_a_list gem which handled positing and ordering of associated records. I checked in forms-admin adn forms- runner and none of the code uses it nor does any newish form include it.
Trello card: 

Remove page_order column from forms table

---

app/models/form.rb
spec/models/form_spec.rb

This is an API fix for the work here https://trello.com/c/9QBLASbG/1331-add-archive-tag 
In order to correctly identify forms with draft versions, the `has_draft_version` method should also include the `archived_with_draft` state!

Fix draft check not including archived_with_draft

---

Gemfile
Gemfile.lock
app/models/form.rb
app/service/task_status_service.rb
db/migrate/20240208124208_add_payment_url_to_forms.rb
db/migrate/20240208134335_add_payment_url_to_made_live_forms.rb
db/schema.rb
spec/models/form_spec.rb
spec/requests/api/v1/forms_controller_spec.rb
spec/service/task_status_service_spec.rb

https://trello.com/c/VEe72eLB/1357-add-backend-code-to-support-saving-payment-links-for-a-form
Adds a column for `payment_url` to forms. This will be used to store a payment link if one is provided from admin - and to trigger and generate the payment page in the runner

Add payment_url to forms

---

app/state_machines/form_state_machine.rb
spec/state_machines/form_state_machine_spec.rb

Trello card: https://trello.com/c/li50etsD/1432-implement-form-unarchiving
Updates the state machine to allow archived and archived_with_draft forms to be made live. This will enable us to implement unarchiving a form in forms-admin.

Allow archived forms to be made live

---

app/controllers/api/v1/forms_controller.rb
app/models/page.rb
app/service/task_status_service.rb
app/state_machines/form_state_machine.rb
spec/factories/forms.rb
spec/models/page_spec.rb
spec/requests/api/v1/forms_controller_spec.rb
spec/service/task_status_service_spec.rb
spec/state_machines/form_state_machine_spec.rb

Trello card: https://trello.com/c/UVCBeTs8/1433-allow-user-to-create-a-draft-for-an-archived-form
This PR:
- Adds a state transition from `archived` -> `archived_with_draft`
- Updates the state of an archived form to `archived_with_draft` when the form or a page of the form is updated
- Returns the appropriate `make_live_status` of the form for an archived form. This will be "Cannot start yet" if there is a draft with incomplete tasks, otherwise it will be "Not started"
You can test this by archiving a form and then clicking "Edit the draft of this form". The task list should show "Not started" for the "Make your changes live" task. If you mark a task as incomplete, this should change to "Cannot start yet".
- Does it work when run on your …

Allow user to create a draft for an archived form

---

Gemfile.lock

Adds x86_64-darwin-23 to the bundle's platforms. This corresponds to macOS v14 Sonoma.

Add x86_64-darwin-23 to platforms

---

db/migrate/20240510092310_make_is_optional_non_nullable.rb
db/schema.rb
spec/factories/pages.rb

Trello card: https://trello.com/c/WjhNHghp/1482-make-this-question-optional-checkbox-isnt-marked-as-optional
This field should always be either `true` or `false` - we don't want to allow `nil` values. This commit makes it non-nullable, and converts the existing `nil` values to `false`.
Shouldn't be merged until https://github.com/alphagov/forms-admin/pull/1143 has gone in

Make is_optional column non-nullable

---

db/seeds.rb

Commit 3ef12e made the `is_optional` non-nullable, so we need to provide a value whenever creating a Page record.
This change meant that `rails db:seed` now fails with an error, this PR fixes that.

Fix database seed

---

lib/tasks/forms.rake
spec/lib/tasks/forms.rake_spec.rb

Trello card: sort of related to https://trello.com/c/xARqWpGD/1558-model-ibca-as-new-organisation
This is a common support task. Previously we had to do this with a manual request to the forms-api. This PR adds a new rake task so that we can perform this support task using `run-task` as we do for other tasks.

Add task for updating the org that owns a form

---

config/routes.rb

Trello card:[add-well-known-securitytxt](https://trello.com/c/SuTQEt4S/186-add-well-known-securitytxt)
This adds a  /.well-known/security.txt in line with [the gds way](https://gds-way.digital.cabinet-office.gov.uk/standards/vulnerability-disclosure.html#vulnerability-disclosure), which helps people report vulnerabilities to cyber.
It does this by redirecting to alphagov's security.txt from `/security.txt.html` and `/.well-known/security.txt.html`
I have tested this locally, and we are redirected to the [security.txt](https://vdp.cabinetoffice.gov.uk/.well-known/security.txt) as expected when visiting the following urls:
- http://localhost:9292/.well-known/security.txt.html
- http://localhost:9292/security.txt.html
- Does it work when run on …

Add /.well-known/security.txt routes

---

Gemfile.lock

Main build was failing due to a CVE
https://github.com/ruby/rexml/security/advisories/GHSA-4xqq-m2hx-25v8 which is fixed in rexml version 3.3.2

Bump rexml from 3.3.1 to 3.3.2

---

app/controllers/api/v1/reports_controller.rb
app/service/features_report_service.rb
config/routes.rb
spec/factories/forms.rb
spec/requests/api/v1/reports_controller_spec.rb
spec/service/features_report_service_spec.rb

Trello card: https://trello.com/c/mrozr2YJ/1652-report-for-the-features-okr
- Adds a new ReportController so that the forms-admin can request reports from the API
- Adds a new features report that provides:
- the total number of live forms
- the number of live forms that use each answer type at least once
- the number of pages that use each answer type (across all live forms)
- the number of live forms with a payment url
- the number of live forms with at least one route
The generated JSON looks like this:
```json
{
"total_live_forms": 3,
"live_forms_with_answer_type": {
"number": 1,
"address": 1,
"date": 1,
"email": 1,
"national_insurance_number": 1,
"phone_number": 1,
"selection": 3,
"organisation_name": 1,
"text": 3,
"name": 1
},
"live_pages_with_answer_type": {
"number": 1,
"address": …
```

Add features report

---

app/controllers/api/v1/pages_controller.rb
app/service/features_report_service.rb
db/migrate/20240801093156_add_is_repeatable_to_pages.rb
db/schema.rb
spec/requests/api/v1/pages_controller_spec.rb
spec/requests/api/v1/reports_controller_spec.rb
spec/service/features_report_service_spec.rb

Trello card: https://github.com/alphagov/forms-admin/pull/1364 
We want to be able to support an "add another answer" feature for questions in forms.
This PR allows a single question to be marked as allowing more than one answer, in the simplest possible way.
Currently there is no support for this attribute in forms-admin or forms-runner, so the best way to test this is with an API client such as httpie or postman.
Also note that https://github.com/alphagov/forms-admin/pull/1364 needs to be merged before this PR, otherwise the end to end tests will break as forms-admin will refuse the new attribute.
- Are …

Add attribute for "add another answer" for a single question

---

app/models/form.rb
db/migrate/20240801123903_add_external_id_to_forms.rb
db/schema.rb
spec/factories/forms.rb
spec/models/form_spec.rb

https://trello.com/c/NNdV9jj3/1681-3-add-unique-form-url-code-column-to-api-3
The first part of adding external IDs for forms - this adds the external ID column, and starts assigning them for newly created forms with the their normal ID. 
The next step is to migrate all existing forms into the same format, so that all forms from that point onwards have an external id, which is equivalent to their current ID.
There aren't any UI aspects to this yet, so a little hard to test - but you can, once pulled down, check that all your existing forms are migrated with no external ID - but new forms are given one. 
- …

1681 3 add unique form url code column to api 3

---

lib/tasks/forms.rake
spec/lib/tasks/forms.rake_spec.rb

https://trello.com/c/UUocDXYa/1680-5-migration-for-existing-form-external-ids-5
This rake task will attribute every form's external id as its id. This is meant to be a task that is run once, and after this https://github.com/alphagov/forms-api/pull/544 has been deployed. 
From that point forwards, all new forms and existing forms will have an `external_id`, which will lead on to the next steps for moving away from exposing our form ids

Add rake task for setting external_id to id for all forms

---

lib/tasks/access_tokens.rake
spec/lib/tasks/access_tokens.rake_spec.rb

We need to remove a developer's access token. At the moment our workflow relies on another dev with a valid token to follow the steps with our access token API. As an API this makes sense for users, but there are situations where no one has an access token and it's just a bit painful.
We don't want to have to do things like run a SQL query or raiding a backup token.
The intention is to use our cli tool which is restricted.
https://trello.com/c/GDNpsobU

Add rake task to remove access token

---

db/schema.rb

In commit 9293a99 the db/schema.rb file was updated with some new `create_table` statements from migrations weren't committed; I think this happened because some local changes were present in the database for changes unrelated to that commit.
We don't actually want these tables in the API database, at least not yet, so we haven't added any migrations for these tables; so these tables shouldn't be in the schema file. This commit removes them.
For developers running forms-api locally they will need to rebuild their development database to incorporate this change. For production systems this commit shouldn't have any effect, as the deployment process uses migrations rather than the schema file.
- Is it …

Remove tables from schema that don't have migrations

---

app/controllers/api/v1/forms_controller.rb
app/models/form.rb
config/routes.rb
db/seeds.rb
lib/tasks/forms.rake
spec/factories/forms.rb
spec/lib/tasks/forms.rake_spec.rb
spec/models/form_spec.rb
spec/requests/api/v1/forms_controller_spec.rb
spec/requests/application_controller_spec.rb

Trello card: https://trello.com/c/ZHGNp5Lk/1774-remove-organisationid-from-forms-api
Forms-admin no longer consumes the `form.organisation_id` - see https://github.com/alphagov/forms-admin/pull/1423.
This PR removes all uses of `form.organisation_id` from the forms-api code. It also sets the `ignored_columns` for the Forms ActiveModel to safely allow the column to be dropped. See the [ActiveRecord documentation](https://api.rubyonrails.org/v7.1.3.4/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-ignored_columns-3D) for usage of `ignored_columns`.
This follows the steps outlined in this [blog](https://andycroll.com/ruby/safely-remove-a-column-field-from-active-record/) to safely remove a column.
Once this is merged, a follow-up PR will include a migration to drop the column …

Prepare for dropping form.organisation_id column

---

app/models/form.rb
db/migrate/20240910115155_remove_organisation_id_from_forms.rb
db/schema.rb

Trello card: https://trello.com/c/ZHGNp5Lk/1774-remove-organisationid-from-forms-api
This column is no longer referenced, and is ignored by the Forms ActiveRecord, so can be safely dropped.

Remove organisation_id column from forms table

---

.github/workflows/test.yml

Trello card: https://trello.com/c/cn9hyatr/1816-update-postgres-service-in-github-actions-workflows 
We are using Postgres 13 in production [[1](https://github.com/alphagov/forms-deploy/blob/2c7da572fd81ba45d1da6672d5423b929864e123/infra/modules/rds/rds.tf#L35)], we should use the same version for our automated tests.

Bump Postgres from 11 to 13

---

lib/tasks/forms.rake

Trello card: https://trello.com/c/DQCipW8q
This PR adds a rake task to update `submission_type` for a given form. This will be a temporary rake task to set the `submission_type` for forms that currently have CSV submission enabled via the per form feature flag.

Add rake task to update submission type

---

app/models/api/v2.rb
app/models/api/v2/form_document.rb
db/migrate/20240916122719_create_api_v2_form_documents.rb
db/schema.rb
spec/factories/api/v2/form_documents.rb
spec/models/api/v2/form_document_spec.rb

Trello card: https://trello.com/c/l48nxEEO/1789-8-add-a-form-documents-table-to-forms-api
This PR just covers creating and settling the table structure and model for form documents. It doesn't try to update the new model with either version of the API and doesn't add new endpoints. These will come in other PRs.
To represent `form_documents` which will be used to model the v2 API we need a new model and database table.
This model will hold the 'content' of a form as a JSON structure. A form can have more than one form_document and will be referenced by its tag.
Tags will be used to represent the different states of a form. For example most forms will have a form_document with a tag draft. Forms which have been made live will have a form with the tag 'live' and archived forms will have a …

Add api_v2_form_documents table and model

---

db/migrate/20240918153233_add_submission_type_to_made_live_forms.rb
db/schema.rb
lib/tasks/forms.rake
spec/lib/tasks/forms.rake_spec.rb

Trello card: https://trello.com/c/DQCipW8q
This PR adds a `submission_type` attribute to the snapshot JSON of every made live form. This is necessary so that forms-runner can safely use this attribute to determine submission type.
This PR also updates the `set_submission_type_to_email_with_csv` rake task to set the `submission_type` to `email_with_csv` for a form's live versions.

Add submission type to live forms

---

spec/factories/api/v2/forms.rb

Tests which create `api_v2_form` factories sometimes fail with the error
`string contains null byte (ArgumentError)`. There isn't much more
context given.
I think this happens because of the way the factory generates the
`external_id` attribute.
Currently it uses:
```ruby
external_id { Faker::String.random(length: 8) }
```
The documentation for Faker says that `String.random` can produce all UTF-8
code points, which would include the null byte.
We can confirm that setting `external_id` with a string containing the null byte causes the
error:
```ruby
FactoryBot::create :api_v2_form, external_id: "\u0000"
```
The error comes from postgres, so only shows up when using `create` not
`build`.
Creating enough `api_v2_forms`, it's generally possible to get the error.
```ruby
strs = (0...100).map …
```

Fix api_v2_form factory to use valid external_id

---

app/service/api/v2/form_document_repository.rb
spec/service/api/v2/form_document_repository_spec.rb

This commit changes the v2 form document repository so that a draft form document can always be retrieved, even if the v1 form returns false to `#has_draft_version`.
This maintains backwards compatibility of v2 API with v1 API and fixes preview links in forms-admin when forms-runner is using v2 API.
Ideally we would in future consider whether this behaviour is what we want, or if the logic can be moved to forms-runner or forms-admin somehow.

Allow getting draft form from v2 API even when form does not have draft version

---

app/services/task_status_service.rb
app/state_machines/form_state_machine.rb
spec/lib/tasks/forms.rake_spec.rb
spec/models/form_spec.rb
spec/requests/api/v1/forms_controller_spec.rb
spec/services/task_status_service_spec.rb
spec/state_machines/form_state_machine_spec.rb

> [!warning] 
> This PR should only be merged after https://github.com/alphagov/forms-admin/pull/1493 has been merged
Trello card: https://trello.com/c/QuqK5jmG/1867-add-new-task-to-share-a-preview-of-your-draft-form-for-drafts-of-new-live-and-archived-forms
This PR makes it so that:
- The task status for the share preview task is "Cannot start yet" if the form has no questions. We want to do this because the link to the preview will show a 404 page if there are no questions.
- The task is set as not completed when a new draft is made of an existing form. We want users to consider sharing a preview of their new draft before they make it live.
- It is mandatory to complete the task before the form is made live. This PR should only be merged after the admin PR to add the task to the task …

Finalise share preview task

---

app/controllers/api/v1/forms_controller.rb
app/controllers/api/v1/pages_controller.rb
app/models/api/v2/form.rb
app/models/form.rb
app/service/api/v2/form_document_sync_service.rb
app/state_machines/form_state_machine.rb
lib/tasks/forms.rake
spec/lib/tasks/forms.rake_spec.rb
spec/requests/api/v1/forms_controller_spec.rb
spec/requests/api/v1/pages_controller_spec.rb
spec/service/api/v2/form_document_sync_service_spec.rb
spec/state_machines/form_state_machine_spec.rb
spec/support/shared_examples/state_machine.rb

Trello card: https://trello.com/c/l48nxEEO/1789-8-add-a-form-documents-table-to-forms-api
This PR adds a migration and inserts calls into the V1 API to ensure the V2 FormDocument models are updated with calls to the current, V1 API.
It's tempting to add callbacks into the `Form` and `Page` model to update `FormDocuments` when they are committed to the database. That ends up being less code but feels more likely to cause issues somewhere along the line. Adding the calls to the controller is more inline with our goal - updating FormDocuments in API calls.
The code to keep the FormDocuments in sync is aiming to keep things simple at the cost of making more database calls. Rather than use separate methods for the migration and ongoing updates, it uses only one.
- Ensure that you consider the …

Update V2 Form models with V1 API endpoints

---

app/services/features_report_service.rb
spec/requests/api/v1/reports_controller_spec.rb
spec/services/features_report_service_spec.rb

Trello card: None, followup from the additional submission types work
Adds the number of forms which have CSV submissions enabled to the features report API which admin consumes.
Needed for https://github.com/alphagov/forms-admin/pull/1523

Add CSV submission to features report

---

db/migrate/20241022154933_add_s3_bucket_region_to_forms.rb
db/schema.rb
lib/tasks/forms.rake
spec/lib/tasks/forms.rake_spec.rb
spec/models/form_spec.rb
spec/requests/api/v1/forms_controller_spec.rb

Trello card: https://trello.com/c/ToXPf8zb/
When using the AWS SDK for Ruby, it is required to provide the bucket region. If the region is different to the region the bucket was created in, we get the following error:
Aws::s3::Errors::PermanentRedirect - The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
Add a column `s3_bucket_region` to the forms table to store the region for the S3 bucket to send form submission data to.

Store s3 bucket region on form

---

app/services/features_report_service.rb
spec/requests/api/v1/reports_controller_spec.rb
spec/services/features_report_service_spec.rb

This adds a new report which will return all forms that contain a question that has `is_repeatable` set to true. This includes forms in draft states only, as we want to get an idea of how this feature is being used even in non-live forms.
Trello card: https://trello.com/c/a2bMFMxU/1827-5-report-when-forms-are-using-add-another-answer-single-qn
This adds an additional report field which will give a few details about every form with a repeatable question. It will bundle each form as a combination of its form id, form name, and then every repeatable question within that form. Each question will have its id and question text bundled up as well. 
This is in order to create a minimal report in admin, which can display the name of a form and the questions' texts, as well as provide links to …

Add full form report for add another answer

---

app/models/condition.rb
spec/models/condition_spec.rb

Trello card: https://trello.com/c/dUkpDNku/1959-allow-conditions-without-answer-value-as-part-of-branch-routing-in-forms-api 
We want to model a branching route in a form as two conditions with the same check page but different routing pages: the condition for the first page reached skips the pages in the first branch if it is met, and the condition for the page at the end of the first branch skips the pages in the second branch. Because the second condition can only be reached in the case where it should skip, it is redundant to specify the answer value, so we want to be able to omit it.
This commit changes the `warning_answer_doesnt_exist` validation so that if a condition is after another condition then `answer_value` is allowed to be `nil`.
- Ensure that you consider the wider …

Allow answer value to be nil for condition reached after another condition

---

db/seeds.rb

we're adding a new end to end test that will test forms with a submission type of s3. There's no front end way to set a form  to a type of s3, so we can't create the form in the e2e tests. Instead, when testing locally, we will use this new seeded form.
[Trello card](https://trello.com/c/64CM50hZ/1921-add-an-e2e-test-for-s3-submissions)

add new form to seeds for end to end testing

---

app/models/page.rb
spec/services/reports/feature_usage_service_spec.rb

Trello card: https://trello.com/c/icJPiPHn/
Adds a `file` answer type. This answer type will ask the user to upload a file for a question.

Add file answer type

---

app/models/condition.rb
spec/models/condition_spec.rb
spec/models/page_spec.rb
spec/requests/api/v1/conditions_controller_spec.rb

Trello card: https://trello.com/c/5kRIGgDY/2581-change-api-validations-for-conditions-to-use-routingpageid-instead-of-checkpageid
The validations used to make sure conditions make sense within a form do not take into account secondary skips.
This creates issues when displaying secondary skips within the page list and can result in forms with loops being made live.
Because the exisitning validation code used the check_page as a reference it could report incorrect errors in two ways.
- It would produce errors which say that a secondary skip is invalid because the route is next to the end route, even when it wasn't
- It would miss loops in forms
Both cases are fixed by changing the validation code to use `routing_page` instead of `check_page`. For exisiting forms with a basic route, this …

Fix condition validations

---

app/controllers/application_controller.rb
config/application.rb
spec/requests/application_controller_spec.rb

Rename the "host" logging field to "hostname". An additional "host" field is added to the logs that go to Splunk for Kenesis. This means we end up with 2 values for "host" making it difficult to filter searches by it.

Rename host logging field

---

Gemfile.lock

https://www.cve.org/CVERecord?id=CVE-2025-27221

Update URI Gem to 1.0.3

---

app/models/condition.rb
db/migrate/20250306120134_add_exit_page_fields_to_conditions.rb
db/schema.rb
db/seeds.rb
spec/models/condition_spec.rb

Trello card: https://trello.com/c/LYs67GUv/2150-add-somewhere-to-store-exit-page-guidance-in-our-database
This PR adds two columns to the Condition model for storing the heading and markdown content for exit pages.
Exit pages will be represented by a Condition with check_page_id, routing_page_id set and a string value, which could be "", for exit_page_markown.
The Condition validation which reports an error when the goto_page is nil has been changed to ignore exit pages.
It doesn't add any other validations we might need for exit pages. The guidance content stored in pages [uses validations which might be useful](https://github.com/alphagov/forms-api/blob/ff61d5a8b84108b872b00fe074c08ad62cab1d19/app/models/page.rb#L75) such as checking the heading is set if the content is set and checks …

Add markdown for exit pages

---

db/seeds.rb

The markdown for the exit page in the database seed didn't have the right spacing for a list.
Trello card: 

Fix markdown in exit page seed

---

app/controllers/api/v1/reports_controller.rb
app/services/reports/feature_usage_service.rb
config/routes.rb
spec/requests/api/v1/reports_controller_spec.rb
spec/services/reports/feature_usage_service_spec.rb

Trello card: [](https://trello.com/c/SgDCKXcY/145-improve-our-feature-reports)
The report to list forms with add another questions is shown on a different page to the main feature usage report. The feature report in forms-admin now sources its data from the `/api/v2/form_documents` endpoint rather than `/api/v1/reports/features`.
So that we can remove `/api/v1/reports/features`, separate the report to list forms with add another answer questions into its own endpoint. We can remove `/features` once forms-admin is using this new endpoint.
- Has all relevant …

Add separate endpoint for add another answer report

---

config/application.rb

Trello card: N/A
Rails uses [prepared statements](https://www.postgresql.org/docs/current/sql-prepare.html) to query the database. By default these use wildcard select statements.
This commonly causes issues when adding new columns - the new column will cause postgres to throw an error  cached plan must not change result type`.
In Rails 7, a new config setting, `enumerate_columns_in_select_statements`, was added. This replaces the wildcard  select statements with explicit calls to each column. See [the Rails PR](https://github.com/rails/rails/pull/41718) for details.
This means that the prepared statements will be regenerated every time a column is added, so postgres won't throw the error.
This PR turns that config setting on for our ActiveRecord models.
We've already done this in …

 Prevent ActiveRecord errors when adding columns

---

app/controllers/api/v1/conditions_controller.rb
spec/requests/api/v1/conditions_controller_spec.rb

https://trello.com/c/MdPcqbFI/2154-allow-form-creators-to-add-an-exit-page-to-a-route
Allow `exit_page_heading` and `exit_page_markdown` when interacting with the conditions endpoint. It's necessary for the exit page work!

Permit exit page heading and markdown for condition endpoint

---

Dockerfile

Trello card: https://trello.com/c/KoHvaEUA/681-aws-m112-ecs-read-only-root-filesystem-configuration
`forms-api` needs to write to a number of directories under `/app/tmp/`, so to avoid iterating and finding out which ones we mount a volume at `/app/tmp/`.

Mount a volume at /app/tmp/

---

Dockerfile

Trello card: https://trello.com/c/KoHvaEUA/681-aws-m112-ecs-read-only-root-filesystem-configuration
AWS ECS documentation [1] shows how volume ownership should be set
[1] https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html

Set the owner of the /app/tmp and /tmp volumes in the Dockerfile

---

config/application.rb
spec/requests/api/v1/pages_controller_spec.rb

Currently we store timestamps with microsecond precision (the default and maximum for PostgreSQL), but over the wire we only send milliseconds (the default for Rails). This is fine for most purposes, but as we're migrating data from forms-api to forms-admin at the moment it's helpful to get the full precision so we can easily compare the contents of the two databases without noise from truncated timestamps.
This commit uses the ActiveSupport configuration parameter to change the `TimeWithZone#as_json` method to return all 6 digits of precision.
- Has all relevant …

Use full precision timestamps in JSON responses

---

app/models/form.rb
app/models/page.rb
spec/models/form_spec.rb

While working on migrating the forms models from forms-api to forms-admin I noticed that the next_page column for a page in the forms-api database is always set to nil.
As far as I can tell this column hasn't been used since before we migrated from grape (see PR #116), when we migrated to grape we switched to using the acts_as_list gem and the position column instead (see commit e8cc03).
I think we should remove this column now.

Prepare next_page column in pages table to be removed

---

app/models/page.rb
db/migrate/20250709114304_remove_next_page_from_pages.rb
db/schema.rb

This column hasn't been used since before we migrated from grape (see PR #116), when we migrated to grape we switched to using the acts_as_list gem and the position column instead (see commit e8cc03).
Let's remove this column now. Note that we do still need the `next_page` attribute in our JSON responses, as it used by consumers, but it is calculated by a method based on the acts_as_list code, we don't need it in our database.
The column was ignored in #791, so is now safe to actually remove the column.

Remove next_page column from pages table

---

app/controllers/api/v1/forms_controller.rb

forms-admin had been assuming that the response from POST-ing to the make_live endpoint is a form object (see for instance https://github.com/alphagov/forms-admin/blob/4ce3b3473dcc48627cf387de156f37d06126a91e/app/services/form_repository.rb#L34-L43), but it's actually the made live form document. This is less useful because it doesn't contain the state (the attribute that is actually changed), and differs from the response that we get from the archive endpoint, even though they're the conceptually similar actions.
This commit changes the response to be the updated form object as expected.
- Are there all …

Change response of /api/v1/forms/:id/make-live

---

app/controllers/application_controller.rb

When the 422 status was initially proposed in [RFC4918](https://datatracker.ietf.org/doc/html/rfc4918) (2007), it was called 'Unprocessable entity'.
When it became a standard in [RFC9110](https://datatracker.ietf.org/doc/html/rfc9110) (2022), it was renamed 'Unprocessable content'.
Rack now supports it as `:unprocessable_content` and [deprecated `:unprocessable_entity` in v3.1.0](https://github.com/rack/rack/blob/main/CHANGELOG.md#deprecated-1). This commit updates it to use the new name.
- Do the end to end tests need updating before these changes will pass?
- Has all …

Rename unprocessable_entity to unprocessable_content
