- README.md
> Add intial readme

- LICENSE
- docs/README.md
As highlighted in #1 we need to add:
- A licence file
- A docs folder
This PR closes #1
> Add additional setup files

- README.md
Also add the dev url into the readme
> Add build and test badges

- .rubocop.yml
- lib/server.rb
Work towards #25 
- Cleans up the forms routes to reduce duplications and allow for nested resources
- Adds pages as a nested resource underneath 
- Adds stub CRUD routes for pages
> Add stub routes for pages

- .rubocop.yml
- db/migrations/2_create_pages_table.rb
- lib/repositories/forms_repository.rb
- lib/repositories/pages_repository.rb
- lib/server.rb
- spec/repositories/forms_repository_spec.rb
- spec/repositories/pages_repository_spec.rb
Forms require the ability to add question page - this PR adds a pages section to the api
relates #25
> add pages to forms

- lib/server.rb
The runner requires this information to load the initial page as well as to navigate between them.
Following this we should look to create tested service objects for this, however as I'm unsure if these are likely to change I've left them untested in the webroutes for now.
> Add start page and next page information

- lib/server.rb
To support the runner, we also need to add "next" to individual pages
> Add next to individual pages

- Gemfile
- Gemfile.lock
- Guardfile
- Makefile
- README.md
Closes #28 
- Adds a Makefile for setup, serving, linting, and running the tests
- Adds additional make recipes for serving/running tests in "watch" mode using `Guard`
> Quality of life updates

- Makefile
- db/migrations/4_add_org.rb
- lib/repositories/forms_repository.rb
- lib/server.rb
- spec/db/migration_3_spec.rb
- spec/db/migration_4_spec.rb
- spec/repositories/forms_repository_spec.rb
- spec/spec_helper.rb
The gds sso org should be saved into the form, so that only members of that organisation can edit/view it.
> add organisation to api

- lib/repositories/forms_repository.rb
- spec/repositories/forms_repository_spec.rb
> Delete associated pages when deleting a form

- manifest.yml
https://github.com/alphagov/paas-csls-splunk-broker/blob/main/docs/user-guide.md
Send forms-api-dev logs to Splunk
> Bind to PaaS Splunk service

- Gemfile.lock
Part of https://github.com/alphagov/forms-runner/pull/76 https://github.com/alphagov/forms-admin/pull/95
> Update bundler to match version being used in admin/runner

- .gitignore
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
I set the initial limit to 95% for the moment
as the current result when running the tests is 99.28%.
95% feels like a balance to striving for good coverage
but not blocking us from getting code merge.
This report will be used by sonarcloud when we
finally introduce it.
> Add simple-cov for code coverage reporting

- .github/workflows/deploy.yml
Made another silly mistake! missed a backslash, sorry
> add backslash to deploy to fix syntax error

- config.ru
Adds the environment (`local`, `dev`, `staging` or `production`) to the Sentry logging.
Trello card: https://trello.com/c/739XCh0O/368-sentry-updates
> Send PaaS environment to Sentry

- Gemfile
- Gemfile.lock
Sentry UI was complaining that we were using outdated SDK
> Update sentry-ruby gem version

- config.ru
- manifest.yml
Fixes an issue with the previous sentry PR - errors in the dev enviroment were coming through as 'local', because the `PAAS_ENVIRONMENT` variable wasn't available in the app.
- [n/a] I've linked this PR to the relevant issue (if mission work)
> Add missing environment variable to manifest

- db/migrations/7_update_datefields.rb
- spec/db/migration_7_spec.rb
Following on from the broken PR: #57
Thanks to @thomasiles for suggesting this in https://github.com/alphagov/forms-api/pull/43
migrations run on execute, so a comprehensive test command would be `make lint test serve`
if rackup fires up, we're good
`docker-compose up` for a compatible db
My `.env` file looks like
```DATABASE_URL=postgres://postgres:password@localhost/postgres```
> update old forms with a created and updated date

- Gemfile
- Gemfile.lock
Was leftover from earlier prototypes
> remove sinatra from gemfile and lock

- lib/api_v1.rb
fixes https://github.com/alphagov/forms-api/issues/68
Co-authored-by: James Sheppard <57200592+james-sheppard-gov-uk@users.noreply.github.com>
> Close all database connections after each request

- db/migrations/011_change_next_page_from_string_to_integer.rb
- lib/repositories/pages_repository.rb
- spec/db/migration_009_spec.rb
- spec/db/migration_011_spec.rb
- spec/repositories/pages_repository_spec.rb
> Update next page to integer

- .github/dependabot.yml
This should only check and create PR for production specific dependency. Anything used for local dev/testing etc will need to manually be updated.
> Add dependabot to our repo

- lib/api_v1.rb
The api will now accept long_list types
Runner PR https://github.com/alphagov/forms-runner/pull/153
> allowlist long_text

- lib/api_v1.rb
Adds 'number' to the list of allowed answer types.
Trello card: https://trello.com/c/tyDQQZ6A/222-add-number-answer-to-a-question-in-the-runner-and-api
> Add number answer type

- lib/api_v1.rb
Fixes an issue where JSON fields were being encoded twice, causing an issue in the runner.
Trello card: https://trello.com/c/VLYnibtv/225-add-selection-question-type-to-runner
> Fix JSON double-encoding issue

- .github/workflows/ruby-on-rails.yml
This is needed to have https://github.com/alphagov/forms-api/actions/runs/3731737834/jobs/6330301401 pass the CI
Trello card:
> Setup a new github workflow for rails-api to use raisl db:migrate

- app/controllers/heartbeat_controller.rb
- config/routes.rb
- ruby-grape-version/lib/server.rb
- ruby-grape-version/spec/lib/server_spec.rb
- spec/request/heartbeat_spec.rb
> Add ping endpoint

- spec/request/heartbeat_spec.rb
> Fix lint issue

- app/controllers/api/v1/forms_controller.rb
> Fix forms permitted params

- app/controllers/api/v1/forms_controller.rb
- spec/request/api/v1/forms_controller_spec.rb
> Fix failing blank param test

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/pages_controller.rb
- app/models/form.rb
- app/models/page.rb
- config/routes.rb
- db/migrate/20221222115349_add_position_to_pages.rb
- db/migrate/20221222115429_update_pages_position_to_existing_order.rb
- db/schema.rb
- spec/factories/pages.rb
- spec/request/api/v1/pages_controller_spec.rb
> Add move up down

- Gemfile
- Gemfile.lock
- config/initializers/config.rb
- config/initializers/sentry.rb
- config/settings.yml
Add sentry exception logging
This change adds new environment variables which need to be set to use
sentry - see the readme.
The PaaS manifest will need to be changed before deployment.
Trello card:https://trello.com/c/Er1U3EF1/390-add-sentry-logging
> Add sentry

- .github/workflows/ruby-on-rails.yml
- Gemfile
- Gemfile.lock
- Makefile
> Add bundler-audit, brakeman and update makefile

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/environments/production.rb
Based of https://github.com/alphagov/forms-admin/pull/183
Trello card:
> Add lograge to rails-api

- .github/workflows/docker_build.yml
- .github/workflows/ruby-on-rails.yml
> Remove old rails-api branch from workflow

- app/controllers/api/v1/pages_controller.rb
- config/routes.rb
This PR makes the way params are handled in the pages controller more regular.
Trello card:
> Refactor page routes to use single param

- config/initializers/sentry.rb
- spec/config/settings_spec.rb
Changes to match what we have in forms-admin
Trello card:
> Tweak Sentry config and add tests

- app/controllers/api/v1/forms_controller.rb
- spec/request/api/v1/forms_controller_spec.rb
This commit makes the forms controller match Pages and reduces some duplication.
Trello card:
> Refactor form controller

- Gemfile
- Gemfile.lock
Not often we bump our dev dependencies. This PR bumps all our dev dependencies.
Trello card:
> Bump dev dependencies

- README.md
- app/service/feature_service.rb
- config/settings.yml
- spec/service/feature_service_spec.rb
- spec/spec_helper.rb
- spec/support/features.rb
This PR adds a feature service to the API - it was part of this PR https://github.com/alphagov/forms-api/pull/184
The original work requires the feature flag service, but this is now going to be introduced in this new PR, which will be merged in prior so that other work that relies on having a feature service can take place.
> Feature service

- db/migrate/20230206101043_convert_answer_settings_from_string_null_to_null.rb
- db/migrate/20230206101956_rerun1_convert_date_to_other_date.rb
- db/migrate/20230206115435_rerun1_convert_address_to_uk_address.rb
- db/migrate/20230206115617_rerun1_convert_old_text_fields_to_new_text_fields.rb
- db/schema.rb
- Sets `answer_settings`  from `"null"` to `null`
- Reruns migrations that convert legacy answer_type to use `answer_settings`
-
Trello card: https://trello.com/c/NhGyugF4/493-fix-null-answersettings
> Migration to update answer_settings from 'null' to null

- app/controllers/api/v1/pages_controller.rb
- db/migrate/20230204150400_drop_question_short_name_from_pages.rb
- db/schema.rb
- spec/migrations/convert_address_to_uk_address_spec.rb
- spec/migrations/convert_date_to_other_date_spec.rb
- spec/migrations/convert_old_text_fields_to_new_text_fields_spec.rb
- spec/request/api/v1/pages_controller_spec.rb
> Remove obsolete question_shorthand_name

- app/controllers/api/v1/access_tokens_controller.rb
- app/controllers/application_controller.rb
- app/models/access_token.rb
- config/environments/production.rb
- config/routes.rb
- db/migrate/20230315200638_add_description_to_access_tokens.rb
- db/migrate/20230317103613_rename_token_to_token_digest_from_access_token.rb
- db/schema.rb
- spec/factories/access_tokens.rb
- spec/models/access_token_spec.rb
- spec/request/api/v1/access_tokens_controller_spec.rb
- adds an optional description to the token when it is created
- adds the tokens owner to the logs if the request has used one of the tokens
- adds an endpoint that will deactivate a specific token 
- renames token column to token_digest
Trello card:
> Multi auth keys part 2

- config/routes.rb
- spec/request/api/v1/pages_controller_spec.rb
> Refactor pages request spec to use rails url helpers

- app/controllers/api/v1/access_tokens_controller.rb
- app/controllers/api/v1/conditions_controller.rb
- app/controllers/api/v1/forms_controller.rb
- app/controllers/api/v1/pages_controller.rb
- app/controllers/application_controller.rb
- app/models/condition.rb
- config/routes.rb
- spec/factories/pages.rb
- spec/request/api/v1/conditions_controller_spec.rb
- spec/request/api/v1/forms_controller_spec.rb
This adds a set of endpoints for the conditions table. It makes use of the rails resource system, so it has all the standard routes. 
Trello card: https://trello.com/c/Y5noSn8H/660-add-conditions-endpoint-to-api
> Add conditions controller

- spec/request/heartbeat_controller_spec.rb
There were a couple of issues with our specs in this repo
- spec filenames didn't match the filenames for the code they were testing
- specs main rspec descriptions where using strings rather than the class name that they were testing
Trello card: https://trello.com/c/hF3wjMvu/594-update-rspec-test-description-to-use-class-names-rather-than-strings
> Refactor spec folder

- README.md
- lib/tasks/code_quality_checks.rake
Adds rake tasks for linting and running tests, and a `run code_quality_checks` task to do them both in parallel. This should make it easier to run them all before committing / pushing your code. There's probably a case for running this task in a git hook but that's a task for another PR.
Trello card: none
- [n/a] I've linked this PR to the relevant issue (if mission work)
> Add rake task for test and linting

- README.md
- app/lib/json_log_formatter.rb
- config/application.rb
- config/environments/production.rb
- spec/lib/json_log_formatter_spec.rb
Structured logging allows simpler searching and reporting from our logs. Introduces a JSON log formatter as per the implementation in forms-runner.
Similar implementation as per: https://github.com/alphagov/forms-runner/pull/371
We should explore ways of sharing common code, happy to revisit this after adding to forms-admin to make sure we have the correct level of reuse before committing to such a thing.
This is running in development environment and produces logs:
- You can run this locally and see the logs in JSON format.
- This is currently deployed in dev environment. 
Trello card: https://trello.com/c/VSdLnRsI/130-firebreak-convert-logs-to-json-structured
> Structured Logging

- README.md
Adds some documentation to get rid of a very old `TODO:` comment
Trello card: none
- [n/a] I've linked this PR to the relevant issue (if mission work)
> Add missing deployment documentation

- app/controllers/api/v1/pages_controller.rb
- app/models/page.rb
- spec/factories/pages.rb
- spec/models/page_spec.rb
Trello card: https://trello.com/c/Cui39aea/949-save-markdown-from-forms-admin-to-forms-api
> Add validation to addition guidance fields

- app/controllers/api/v1/pages_controller.rb
- config/locales/en.yml
This was missed off as part of https://github.com/alphagov/forms-api/pull/325
> Pages update action should match create action

- .github/workflows/test.yml
This PR makes a few minor and stylistic changes to the `test.yaml` GitHub workflow to make it easier to diff it with the `test.yaml` workflow in our other app repos.
> Make test workflow file more consistent with our other repos

- Gemfile.lock
Bumping to this version in prep for migrating rails from 7.0.8 to 7.1.1
Trello card: 
> Bump paper_trail 15.1.0 (was 15.0.0)

- spec/requests/api/v1/conditions_controller_spec.rb
- spec/requests/heartbeat_controller_spec.rb
I spotted a few places where we were not using rails path helpers. I've checked a using find `got ` , `post `, `put ` & `delete `
Trello card: 
> Use rails path helpers in specs instead of hard coding them

- Dockerfile
- Gemfile.lock
This PR makes a few tweaks to the Dockerfile to make it easier to use with Docker Compose and the update_app_versions script in forms-deploy.
The changes here should be similar to those in alphagov/forms-admin#905.
> Refactor Dockerfile

- app/controllers/api/v2/form_documents_controller.rb
- app/controllers/api/v2/forms_controller.rb
- app/models/api/v2/form.rb
- app/service/api/v2/converter.rb
- app/service/api/v2/form_document_repository.rb
- config/routes.rb
- spec/factories/api/v2/forms.rb
- spec/models/api/v2/form_spec.rb
- spec/requests/api/v2/form_documents_controller_spec.rb
- spec/requests/api/v2/forms_controller_spec.rb
- spec/routing/api/v2/form_documents_routing_spec.rb
- spec/routing/api/v2/forms_routing_spec.rb
- spec/service/api/v2/converter_spec.rb
- spec/service/api/v2/form_document_repository_spec.rb
Trello card: https://trello.com/c/hVUvYkB3/1722-8-create-v2-api-get-endpoints-in-forms-api 
Add `GET /api/v2/forms`, `GET /api/v2/forms/:id`, and `GET /api/v2/forms/:id/{draft, live, archived}`, as described in [ADR034].
This PR adds an `Api::V2::Form` model that uses the same data as the existing v1 Form model, and an `Api::V2::FormDocumentRepository` to be able to retrieve v2 form documents from snapshots of v1 forms. There is also a `Api::V2::Converter` service object to hold the logic related to converting from one JSON object format to the other.
See the commit messages for more details on the changes.
I've tested this in dev, I also stress tested the converter by running 100 live forms from the production database through it with the following script:
```bash
forms data_api -d …
```
> Add v2 API endpoints to get forms and form documents

- app/controllers/api/v1/conditions_controller.rb
- spec/requests/api/v1/conditions_controller_spec.rb
When the conditions controller as part of V1 API is called to create, update or destroy a condition, the form document should be updated to reflect the change.
This commit adds calls to the controller to the FormDocumentSyncService to ensure the form document is updated.
The Condition model has methods which save and update the form. It's an option to extend these methods to update the form document.
This would make these methods more complicated, so the calls are put in the controller to match the calls in the page controller.
This should ensure that all methods which the admin calls are covered.
Here is a list of the Controller and actions which are called from the admin from the last 30 days prised out of splunk:
```
Api::V1::ConditionsController-create …
```
> Update FormDocuments when changing conditions

- db/seeds.rb
Set `share_preview_completed` field to true on the form created by the seed data so the form can be made live. We recently added this field to support a new mandatory task that must be completed before forms can be made live.
> Fix seed data

- db/seeds.rb
For local developer setups, this make it easier to see what branching looks like, by adding an example form with branching to the database seed.
> Add form with branch routing to database seed

- .github/workflows/test.yml
- Gemfile
- Gemfile.lock
Combines PRs
- #745
- #746
- #749
- #751
- #752
- #753
- #754
> Batch dependency updates

- Dockerfile
Trello card: https://trello.com/c/KoHvaEUA/681-aws-m112-ecs-read-only-root-filesystem-configuration
So that the application can write to it when the filesystem is otherwise readonly
> Add a volume for /app/tmp/cache in Dockerfile
